#!/usr/bin/env python
# coding: utf-8

# # Basic libraries
# 
# `miepython` is going to form the basis of our comparisons.

# In[178]:


import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import miepython


# In[179]:


# speed of light

c0 = 3e17


# # Scattering cross section from Goma
# 
# Read our flux file `sigma_scattering.out` from goma
# 
# This is generated by the Scattering Cross Section flux post processing.
# 
# We will plot based on the order in the file.

# In[180]:


with open('sigma_scattering.out') as f:
    lines = f.readlines()
    ll = len(lines)
    index = 0
    times = []
    names = []
    fluxes = []
    areas = []
    while index + 2 < ll:
        line = lines[index]
        s = line.strip().split(" ")
        if s[0] == "Time/iteration":
            time = float(s[2])
            l1 = lines[index + 1].strip().split()
            assert (l1[1] == "Side_Set")
            name = l1[0]
            l2 = lines[index + 2].strip().split()
            assert (l2[0] == "flux=")
            flux = float(l2[1])
            area = float(l2[4])
            index += 2
            times.append(time)
            names.append(name)
            fluxes.append(flux)
            areas.append(area)
        else:
            index += 1

assert (len(set(names)) == 1)

data_dict = {
    'lambda': c0 / np.array(times),
    'cross_section': fluxes,
    'area': areas,
}

data = pd.DataFrame.from_dict(data_dict)
data


# # Absorption cross section from Goma
# 
# Read our volume integration file `abs_cs.out` from goma
# 
# This is generated by the Absorption Cross Section volume integration post processing.
# 
# We will plot based on the order in the file.

# In[181]:


with open('abs_cs.out') as f:
    lines = f.readlines()
    ll = len(lines)
    index = 0
    times = []
    names = []
    fluxes = []
    areas = []
    while index + 2 < ll:
        line = lines[index]
        s = line.strip().split(" ")
        if s[0] == "Time/iteration":
            time = float(s[2])
            l1 = lines[index + 1].strip().split()
            assert (l1[1] == "Volume")
            name = l1[0]
            l2 = lines[index + 2].strip().split()
            assert (l2[0] == "volume=")
            flux = float(l2[1])
            #area = float(l2[4])
            index += 2
            times.append(time)
            names.append(name)
            fluxes.append(flux)
            #areas.append(area)
        else:
            index += 1

assert (len(set(names)) == 1)

data_dict = {
    'lambda': c0 / np.array(times),
    'cross_section': fluxes,
}

abs_data = pd.DataFrame.from_dict(data_dict)
abs_data


# # Reference values for Gold
# 
# from [https://refractiveindex.info/?shelf%20=%20main&book%20=%20Au&page%20=%20Johnson](https://refractiveindex.info/?shelf%20=%20main&book%20=%20Au&page%20=%20Johnson)

# In[182]:


# wavelength in microns
ref_lam = np.array([ 0.1879, 0.1916, 0.1953, 0.1993, 0.2033, 0.2073, 0.2119,
    0.2164, 0.2214, 0.2262, 0.2313, 0.2371, 0.2426, 0.249, 0.2551, 0.2616, 0.2689,
    0.2761, 0.2844, 0.2924, 0.3009, 0.3107, 0.3204, 0.3315, 0.3425, 0.3542, 0.3679,
    0.3815, 0.3974, 0.4133, 0.4305, 0.4509, 0.4714, 0.4959, 0.5209, 0.5486, 0.5821,
    0.6168, 0.6595, 0.7045, 0.756, 0.8211, 0.892, 0.984, 1.088, 1.216, 1.393, 1.61,
    1.937, ])

ref_n = np.array([ 1.28, 1.32, 1.34, 1.33, 1.33, 1.3, 1.3, 1.3, 1.3, 1.31, 1.3,
    1.32, 1.32, 1.33, 1.33, 1.35, 1.38, 1.43, 1.47, 1.49, 1.53, 1.53, 1.54, 1.48,
    1.48, 1.5, 1.48, 1.46, 1.47, 1.46, 1.45, 1.38, 1.31, 1.04, 0.62, 0.43, 0.29,
    0.21, 0.14, 0.13, 0.14, 0.16, 0.17, 0.22, 0.27, 0.35, 0.43, 0.56, 0.92, ])

ref_k = np.array([ 1.188, 1.203, 1.226, 1.251, 1.277, 1.304, 1.35, 1.387, 1.427,
    1.46, 1.497, 1.536, 1.577, 1.631, 1.688, 1.749, 1.803, 1.847, 1.869, 1.878,
    1.889, 1.893, 1.898, 1.883, 1.871, 1.866, 1.895, 1.933, 1.952, 1.958, 1.948,
    1.914, 1.849, 1.833, 2.081, 2.455, 2.863, 3.272, 3.697, 4.103, 4.542, 5.083,
    5.663, 6.35, 7.15, 8.145, 9.519, 11.21, 13.78, ])


# # Comparison between Goma and MiePython

# In[185]:


radius = 0.1  # in microns
m = ref_n - 1.0j * ref_k
x = 2 * np.pi * radius / ref_lam
cross_section_area = np.pi * radius**2
mu_a = 4 * np.pi * ref_k / ref_lam  # nm
qext, qsca, qback, g = miepython.mie(m, x)
umsq_to_nmsq = 1000*1000
nmsq_to_umsq = 1.0/umsq_to_nmsq

#sca_cross_section = qsca  * cross_section_area * umsq_to_nmsq
#abs_cross_section = (qext - qsca) * cross_section_area * umsq_to_nmsq
sca_cross_section = qsca  * cross_section_area
abs_cross_section = (qext - qsca) * cross_section_area

plt.figure()
plt.plot(ref_lam * 1000, sca_cross_section, "sr", label='MiePython')
plt.plot(data['lambda'],
#         data['cross_section'],
         data['cross_section']*nmsq_to_umsq,
         lw=1,
         marker='x',
         label='Goma')
plt.xlabel("Wavelength (nm)")
plt.ylabel("Cross Section (um^2)")
plt.title('Scattering cross section comparison')
plt.legend()
plt.show()

plt.figure()
plt.plot(ref_lam * 1000, abs_cross_section, "ob", label='MiePython')
plt.xlabel("Wavelength (nm)")
plt.ylabel("Cross Section (um^2)")
plt.title("Absoprtion cross section comparison")
plt.plot(abs_data['lambda'],
#         abs_data['cross_section'],
         -abs_data['cross_section']*nmsq_to_umsq,
         lw=1,
         marker='x',
         label='Goma')
plt.legend()
cross_section_area
plt.show()


# In[ ]:




