%% Import data from text file.
% Script for importing data from the following text file:
%
%    /gpfs/ccparri/drying/dakota/toluene/pvac_seq/testing/test4/baseall/base1/plotFile.dat
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2022/05/06 12:51:50

%% Initialize variables.
filename = 'plotFile.dat';
opt = 'line';
%opt = 'scatter';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%13f%21f%17f%13f%17f%17f%17f%C%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Time = dataArray{:, 1};
Prediction = dataArray{:, 2};
Experiment = dataArray{:, 3};
Tbase = dataArray{:, 4};
Tsurf = dataArray{:, 5};
Cbase= dataArray{:, 6};
Csurf = dataArray{:, 7};
VarName8 = dataArray{:, 8};

Time4 = Time;
Prediction4 = Prediction;
Experiment4 = Experiment;
Tbase4 = Tbase;

%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;

opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "time_T";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("temp_T.txt", opts);

time_T = tbl.time_T;
ETime4 = time_T;
clear opts tbl

%%

opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "temp";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("temp.txt", opts);

temp = tbl.temp;
ETemp4 = temp;
clear opts tbl

%%

fig = figure(1);
    ax = gca;
    hold(ax,"off");
    if matches(opt,"scatter")
        plt(1) = scatter(Time,Experiment,50,'MarkerEdgeColor','blue','MarkerFaceColor','red');
    else
        plt(2) = plot(Time,Experiment,'LineWidth',2,'LineStyle','-','Color','red');
    end
    hold(ax,"on");
    plt(2) = plot(Time,Prediction,'LineWidth',2,'LineStyle','-','Color','black');
    
saveas(fig,'base1.png');
save('base4.mat','Time4','Prediction4','Experiment4','Tbase4','ETime4','ETemp4');
